import Link from 'next/link'
import Script from 'next/script'
import Head from 'next/head'







export default function Temporary_Join_Signin(){
  return (
    <>


<div id="join-signin_container">
  <div className="forms ">
    <div id="join-container">
      <h1>Join Hello</h1>
      <div id="input-container1" className="input-containers">
        <ion-icon name="person-outline" />
        <input type="search" name="op1o1" placeholder="Enter Name" id="op1o1" />
      </div>
      <div id="input-container2" className="input-containers">
        <ion-icon name="mail-outline" />
        <input type="search" name="op1o1" placeholder="Enter Email" id="op1o1" />
      </div>
      <div id="input-container5" className="input-containers">
        <ion-icon name="key-outline" />
        <input type="search" name="op1o1" placeholder="Enter Password" id="op1o1" />
      </div>
      <div id="input-container6" className="input-containers">
        <ion-icon name="refresh-outline" />
        <input type="search" name="op1o1" placeholder="Enter Cpassword" id="op1o1" />
      </div>
      <div id="others-container">
        <div id="btn">Next</div>
        <div id="or-container">
          <div id="line1" />
          <h1> or </h1>
          <div id="line2" />
        </div>
        <div id="wallet_connect-login-container">
          <div id="wallet_connect-login-button">
            Connect to WalletConnect
          </div>
        </div>
        <div id="social-login-container">
          <div id="social_login_header">
            <img src="../../public/Google.png" alt="google-icon" width={48} height={48} />
            <img src="../../public/Facebook.png" alt="linkedin-icon" width={48} height={48} />
            <div className="circle">
              <ion-icon name="caret-down" />
            </div>
          </div>
          <div id="social_login_toolbar">
            <img src="../../public/Discord.png" alt="google-icon" width={48} height={48} />
            <img src="../../public/Messanger.png" alt="linkedin-icon" width={48} height={48} />
            <img src="../../public/Linkedin.png" alt="Linkin" width={48} height={48} />
          </div>
        </div>
        <h2>Already a membar?<a href="#" id="join_toggle" className="join_signin_toggle">Signin</a></h2>
      </div>
    </div>
    <div id="signin-container">
      <h1>Signin Hello</h1>
      {/* <div id="input-container1" class="input-containers">
              <ion-icon name="person-outline"></ion-icon>
              <input type="search" name="op1o1" placeholder="Enter Name" id="op1o1">
          </div> */}
      <div id="input-container2" className="input-containers">
        <ion-icon name="mail-outline" />
        <input type="search" name="op1o1" placeholder="Enter Email" id="op1o1" />
      </div>
      <div id="input-container3" className="input-containers">
        <ion-icon name="key-outline" />
        <input type="search" name="op1o1" placeholder="Enter Password" id="op1o1" />
      </div>
      <div id="others-container">
        <div id="btn">Next</div>
        <div id="or-container">
          <div id="line1" />
          <h1> or </h1>
          <div id="line2" />
        </div>
        <div id="wallet_connect-login-container">
          <div id="wallet_connect-login-button">
            Connect to WalletConnect
          </div>
        </div>
        <div id="social-login-container">
          <div id="social_login_header">
            <img src="../../public/Google.png" alt="google-icon" width={48} height={48} />
            <img src="../../public/Facebook.png" alt="linkedin-icon" width={48} height={48} />
            <div className="circle">
              <ion-icon name="caret-down" />
            </div>
          </div>
          <div id="social_login_toolbar">
            <img src="../../public/Discord.png" alt="google-icon" width={48} height={48} />
            <img src="../../public/Messanger.png" alt="linkedin-icon" width={48} height={48} />
            <img src="../../public/Linkedin.png" alt="Linkin" width={48} height={48} />
          </div>
        </div>
        <h2>Not a membar?<a href="#" id="signin_toggle" className="join_signin_toggle">Join</a></h2>
      </div>
    </div>
  </div>
</div>

























      <Script
        src="https://cdn.jsdelivr.net/gh/Harry1o1/Demo/nextjs/containers/Join&Signin/main.js"
        strategy="beforeInteractive"
      />

      <Head>
        <title>LetWorkBeDone</title>
        <meta name="description" content="Generated by create next app" />

        
        <link href="https://cdn.jsdelivr.net/gh/Harry1o1/Demo/nextjs/containers/Join&Signin/style.css" rel="stylesheet" />

        
        
        

      </Head>

    </>
  );
};

