
import Navbar from "./navbar";
import Navbar1 from "./Navbars/navbar1";
import Footer1 from '../containers/Footer/Footer';


import Link from 'next/link'
import Script from 'next/script'
import Head from 'next/head'
// import Document, { Html, Head, Main, NextScript } from 'next/document'

// opbro🎉🎉🎉🎉😎😎😎😎





export default function Layout({ children }) {
  return (
    <>

      {/* Testing🖖🖖🖖 */}
      
      <Script
        type="module" src="https://cdn.jsdelivr.net/gh/Harry1o1/Demo/nextjs/ux/globals.js"
        strategy="beforeInteractive"
      />
            
          {children}


      <Head>
        <title>LetWorkBeDone</title>
        <meta name="description" content="Generated by create next app" />

        <link href='https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css' rel='stylesheet' />

        
        

      </Head>

    </>
  );
};

